### ISSUE TITLE
How to change 'save to phone' to 'Add to google wallet'?

### ISSUE THREAD

**Issue by abhigk** [google-wallet/save-to-google-pay-button#13]
How to change 'save to phone' to 'Add to google wallet'?

Now google has changed from Google Pay to Google wallet.
I want to do the same and change it on my react application.

This question is related to:

- [ ] React component (`@google-pay/save-button-react`)

**Comment by dmengelt** [comment]
@abhigk / @sarkamrav we fixed this now. please take a look here: https://gpay-live-demo.web.app/customize-save.html
